import { StyleSheet } from "react-native";

export default StyleSheet.create({
  containerPai: {
    flex: 1,
    backgroundColor: "#012E40",
  },
  wrapperHeader: {
    paddingHorizontal: 20,
  },
  headerMain: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  plantaoContainer: {
    flex: 1,
  },
  headerFilhoContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    paddingHorizontal: 10,
    justifyContent: "space-between",
    marginTop: 20,
  },
  headerTitle: {
    display: "flex",
    flexDirection: "row",
  },
  containerConcluidas: {
    paddingHorizontal: 10,
  },
  flatListContainer: {
    width: "100%",
    paddingHorizontal: 10,
  },
  plantaoTitle: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  plantaoItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    margin: 5,
    backgroundColor: "#103d4a",
    padding: 10,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  mainContainer: {
    flexDirection: "row",
    display: "flex",
    flex: 1,
    marginRight: 10,
    paddingRight: 18,
    borderRightWidth: 1,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
  },
  containerIcons: {
    flexDirection: "column",
    alignItems: "center",
    gap: 3.5,
  },
  containerInfos: {
    flexDirection: "column",
    alignItems: "flex-start",
  },
  medicoContainer: {
    display: "flex",
    alignItems: "center",
    flex: 2,
  },
  plantaoDate: {
    fontSize: 13,
    color: "#59994e",
  },
  plantaoTurno: {
    fontSize: 13,
    color: "#ffffff",
  },
  plantaoMedico: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
  },
  plantaoFuncao: {
    alignSelf: "center",
    fontSize: 13,
    color: "#bfb9a6",
  },
  plantaoLocal: {
    fontSize: 13,
    color: "#ffffff",
  },
  addButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#59994e",
    width: 50,
    height: 50,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5, // Sombra no Android
    shadowColor: "#000", // Sombra no iOS
    shadowOffset: { width: 7, height: 7 },
    shadowOpacity: 0.7,
    shadowRadius: 5,
  },
  addButtonText: {
    fontSize: 25,
    color: "#030302",
    fontWeight: "bold",
    paddingBottom: 5,
  },
  modalContent: {
    backgroundColor: "#012E40",
    padding: 20,
    alignItems: "center",
    height: "95%",
    position: "absolute",
    bottom: 0,
  },
  headerContainer: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 35,
    width: "100%",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#ffffff",
  },
  dropDownListContainerMedico: {
    maxHeight: 355,
  },
  dropDownListContainerFuncao: {
    height: 210,
    maxHeight: 210,
  },
  dropDownListContainerLocal: {
    height: 250,
    maxHeight: 240,
  },
  containerDataHora: {
    display: "flex",
    flexDirection: "row",
    gap: 30,
  },
  buttonSeletor: {
    backgroundColor: "#d1d8e3",
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 20,
  },
  inputBoxPickerMedico: {
    width: "100%",
    height: 40,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: "#d1d8e3",
    justifyContent: "center",
  },
  inputBoxPickerFuncao: {
    width: "100%",
    height: 40,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: "#d1d8e3",
    justifyContent: "center",
  },
  inputBoxPickerLocal: {
    width: "100%",
    height: 40,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: "#d1d8e3",
    justifyContent: "center",
  },
  inputText: {
    fontSize: 17,
  },
  placeholderText: {
    color: "#191a1c",
    fontSize: 13,
  },
  inputLabel: {
    position: "absolute",
    left: 10,
    color: "#ccc",
  },
  filledText: {
    color: "#000",
  },

  iconEdit: {
    position: "absolute",
    right: 10,
    top: "25%",
  },
  containerHora: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
  },
  containerMedico: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
    zIndex: 300,
  },
  containerFuncao: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
    zIndex: 200,
  },
  containerLocal: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
    zIndex: 100,
  },
  closeText: {
    color: "white",
    fontSize: 16,
  },
  confirmarPlantaoButton: {
    backgroundColor: "#111827",
    display: "flex",
    width: "100%",
    borderWidth: 1,
    borderColor: "transparent",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    marginTop: 20,
  },
  buttonDisabled: {
    backgroundColor: "#ddd",
    opacity: 0.2,
  },
  buttonTextDisabled: {
    color: "black",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 24,
  },
  confirmarPlantaoText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 24,
  },
  betweenInput: {
    marginTop: 15,
    marginBottom: 15,
  },
  concluidoText: {
    color: "green",
    fontSize: 15,
  },
});
